services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:gluetun
    env_file:
      - .env
    volumes:
      - ${CONFIG_DIRECTORY}/qbittorrent:/config
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - ${TORRENTS_DIRECTORY}:/torrents
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - WEBUI_PORT=${WEBUI_PORT}
#      - TORRENTING_PORT=6881
#    mem_limit: 8g
#    cpus: 0.25
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
    depends_on:
      - gluetun  
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 1m30s
#      timeout: 20s
#      retries: 5
#      start_period: 2m
    restart: unless-stopped

  gluetun:
    container_name: gluetun    
    image: qmcgaw/gluetun:v3
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    ports:
      # Mousehole port
      - ${MOUSE_PORT}:5010 
      # qbittorrent port
      - ${WEBUI_PORT}:8080
    volumes:
      - ${CONFIG_DIRECTORY}/gluetun:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Canada #Netherlands,Sweden,Norway,Switzerland
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=${VPN_SERVICE_PROVIDER}

      # qBittorrent port forwarding
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8080/api/v2/app/setPreferences'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- -nv --retry-connrefused --post-data "json={\"listen_port\":0,\"current_network_interface\":\"lo\"}" http://127.0.0.1:8080/api/v2/app/setPreferences'
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  mousehole:
    container_name: mousehole    
    image: tmmrtn/mousehole:latest
    network_mode: service:gluetun
    env_file:
      - .env
    volumes:
      # persist cookie data across container restarts
      - "mousehole:/var/lib/mousehole"    
    environment:
      - TZ=America/Chicago
      - MOUSEHOLE_AUTH_PASSWORD=${MOUSEHOLE_AUTH_PASSWORD}
      - MOUSEHOLE_ALLOWED_HOSTS=${MOUSEHOLE_ALLOWED_HOSTS}
      - MOUSEHOLE_ALLOWED_ORIGINS=${MOUSEHOLE_ALLOWED_ORIGINS}
    restart: unless-stopped

volumes:
    mousehole: