services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - .env
    ports:
      - ${PROWLARR_PORT}:${PROWLARR_PORT}
    volumes:
      - ${CONFIG_DIRECTORY}/Prowlarr:/config
      - ${DOWNLOADS_DIRECTORY}:/downloads        
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    env_file:
      - .env
    ports:
      - ${JACKETT_PORT}:${JACKETT_PORT}  
    volumes:
      - ${CONFIG_DIRECTORY}/Jackett:/config
      - ${DOWNLOADS_DIRECTORY}:/downloads        
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS= #optional
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - .env
    ports:
      - ${FLARESOLVERR_PORT}:${FLARESOLVERR_PORT}  
    volumes:
      - ${CONFIG_DIRECTORY}/Flaresolverr:/config        
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - .env
    ports:
      - ${BAZARR_PORT}:${BAZARR_PORT}    
    volumes:
      - $CONFIG_DIRECTORY}/bazarr:/config
      - ${DATA_DIRECTORY}/movies:/movies #optional
      - ${DATA_DIRECTORY}/tv:/tv #optional
      - ${DATA_DIRECTORY}/anime:/anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    restart: unless-stopped
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - .env
    ports:
      - ${RADARR_PORT}:${RADARR_PORT}   
    volumes:
      - ${CONFIG_DIRECTORY}/Radarr:/config
      - ${DOWNLOADS_DIRECTORY}:/downloads
      - ${DATA_DIRECTORY}/movies:/movies       
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file:
      - .env
    ports:
      - ${SONARR_PORT}:${SONARR_PORT}    
    volumes:
      - ${CONFIG_DIRECTORY}/Sonarr:/config
      - ${DOWNLOADS_DIRECTORY}:/Downloads
      - ${DATA_DIRECTORY}/tv:/tv
      - ${DATA_DIRECTORY}/anime:/anime      
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - UMASK_SET=022
    restart: unless-stopped

#  lidarr:
#    image: lscr.io/linuxserver/lidarr:latest
#    container_name: lidarr
#    env_file:
#      - .env
#    ports:
#      - ${LIDARR_PORT}:${LIDARR_PORT}    
#    volumes:
#      - ${CONFIG_DIRECTORY}/lidarr:/config
#      - ${DATA_DIRECTORY}/music:/music #optional
#      - ${DOWNLOADS_DIRECTORY}:/downloads #optional
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=America/Chicago
#    restart: unless-stopped