services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    env_file:
      - .env
    ports:
      - ${MEALIE_PORT}:9000
    volumes:
      - ${DATA_DIRECTORY}/recipes:/app/data/
      - ${CONFIG_DIRECTORY}/mealie:/config
    environment:
      - ALLOW_SIGNUP="false"
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - BASE_URL=${BASE_URL}
#    deploy:
#      resources:
#        limits:
#          memory: 1000M
    restart: always