services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    env_file:
      - .env
    ports:
      - ${MEALIE_PORT}:9000
    volumes:
      - /home/xerxys/mediaserver/plex/data/recipes:/app/data/
      - /home/xerxys/mediaserver/config/mealie:/config
    environment:
      - ALLOW_SIGNUP="false"
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - BASE_URL=${BASE_URL}
#    deploy:
#      resources:
#        limits:
#          memory: 1000M
    restart: always