services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    # ABS runs on port 13378 by default. If you want to change
    # the port, only change the external port, not the internal port
    env_file:
      - .env
    ports:
      - ${ABS_PORT}:80
    volumes:
      # These volumes are needed to keep your library persistent
      # and allow media to be accessed by the ABS server.
      # The path to the left of the colon is the path on your computer,
      # and the path to the right of the colon is where the data is
      # available to ABS in Docker.
      # You can change these media directories or add as many as you want
      - ${AUDIOBOOK_LIBRARY}:/audiobooks
      - ${ABS_PODCAST_LIBRARY}:/podcasts
      # The metadata directory can be stored anywhere on your computer
      - ${ABS_CONFIG_DIRECTORY}/metadata:/metadata
      # The config directory needs to be on the same physical machine
      # you are running ABS on
      - ${ABS_CONFIG_DIRECTORY}:/config
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    # You can use the following environment variable to run the ABS
    # docker container as a specific user. You will need to change
    # the UID and GID to the correct values for your user.
    #environment:
    #  - user=1000:1000

  readmeabook:
    image: ghcr.io/kikootwo/readmeabook:latest
    container_name: audiobookseerr
    env_file:
      - .env
    ports:
      - ${RMAB_PORT}:${RMAB_PORT}
    volumes:
      - ${RMAB_CONFIG_DIRECTORY}:/app/config
      - ${RMAB_CONFIG_DIRECTORY}/cache:/app/cache
      - ${DOWNLOADS_DIRECTORY}:/downloads                          # Your download client's path
      - ${AUDIOBOOK_LIBRARY}:/media                   # Your audiobook library
      - pgdata:/var/lib/postgresql/data                                        #NAMED VOLUME    location -->   /var/lib/docker/volumes/pgdata/_data
      - ${RMAB_CONFIG_DIRECTORY}/redis:/var/lib/redis
    environment:
      - PUID=${PUID}                      # Optional: your user ID
      - PGID=${PGID}                      # Optional: your group ID
      - PUBLIC_URL=${PUBLIC_URL}          # Required for OAuth
    restart: unless-stopped    

volumes:
  pgdata: