services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/xerxys/mediaserver/config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - /mnt/primary:/mnt/default
      - /mnt/secondary:/mnt/tv
      - /home/xerxys/mediaserver/downloads:/mnt/downloads
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,homepage.prince-pillai.com,prince-pillai.com,192.168.86.240:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000
      PGID: 1000
    restart: unless-stopped