services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_DIRECTORY}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - ${PRIMARY_MOUNT}:/mnt/default
      - ${SECONDARY_MOUNT}:/mnt/tv
      - ${DOWNLOADS_DIRECTORY}:/mnt/downloads
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS} # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped