services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${CONFIG_DIRECTORY}/jellyfin:/config
      - ${CACHE_DIRECTORY}/jellyfin:/cache
      - ${DATA_DIRECTORY}/tv:/media/tv  #
      - ${DATA_DIRECTORY}/movies:/media/movies  #
      - ${DATA_DIRECTORY}/anime:/media/anime
      - ${DATA_DIRECTORY}/music:/media/music
      - ${DATA_DIRECTORY}/audiobooks:/media/audiobooks
      - ${DATA_DIRECTORY}/live-tv/epg:/media/epg
#      - type: bind
#        source: /home/xerxys/mediaserver/plex/data
#        target: /media
#        read_only: true
#      - NVIDIA_VISIBLE_DEVICES=all # Passes all GPUs
#      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
#    runtime: nvidia # Required for Docker < 19.03
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    ports:
      - ${SEERR_PORT}:5055  
    volumes:
      - ${CONFIG_DIRECTORY}/jellyseerr:/app/config        
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=${SEERR_PORT} #optiona
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped