services:
  grimmory:
    image: grimmory/grimmory:latest
    container_name: grimmory
    ports:
      - ${SERVER_PORT}:6060
    env_file:
      - .env 
    volumes:
      - ${CONFIG_DIRECTORY}/grimmory:/app/data
      - ${DATA_DIRECTORY}/books:/books
      - ${BOOKDROP_DIRECTORY}:/bookdrop
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=America/Chicago
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    env_file:
      - .env 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${CONFIG_DIRECTORY}/grimmory/mariadb/config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark-grimmory
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MAX_CONCURRENT_DOWNLOADS=1
#      - NODE_ENV=production
      - HIDE_LOCAL_AUTH=true    # Hide the local login form
      - DISABLE_LOCAL_AUTH=true # Disable username/password login
      - OIDC_AUTO_REDIRECT=true  # Skip login page, redirect straight to OIDC
    ports:
      - 6061:8084
    volumes:
      - ${BOOKDROP_DIRECTORY}:/bookdrop # Default destination for book downloads
      - ${CONFIG_DIRECTORY}/shelfmark-grimmory:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - ${DOWNLOADS_DIRECTORY}:/downloads
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb' 
    restart: unless-stopped